name: Build and Deploy Azure Function (Java)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # =====================================================
  # JOB 1 - BUILD
  # =====================================================
  build:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Azure Function
        run: mvn clean package -DskipTests         
        
      - name: Upload function package
        uses: actions/upload-artifact@v4
        with:
          name: function-package
          path: target/azure-functions/local-build
            
  # =====================================================
  # JOB 2 - DEPLOY
  # =====================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-package
          path: function-package
      
      - name: Prepare package
        run: |
          rm -f function-package/local.settings.json
          cd function-package
          zip -r function.zip .
          
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Configure Environment Variables'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.FUNCTION_APP_NAME }}
          app-settings-json: |
            [
              {
                "name": "MONGODB_URI",
                "value": "${{ secrets.MONGODB_URI }}",
                "slotSetting": false
              },
              {
                "name": "MONGODB_DB",
                "value": "${{ secrets.MONGODB_DB }}",
                "slotSetting": false
              },
              {
                "name": "MONGODB_COLLECTION",
                "value": "ratings",
                "slotSetting": false
              },
              {
                "name": "SERVICE_BUS_CONNECTION",
                "value": "${{ secrets.SERVICE_BUS_CONNECTION }}",
                "slotSetting": false
              }
            ]

      - name: Deploy Azure Function (Flex)
        env:
          FUNCTION_APP_NAME: ${{ vars.FUNCTION_APP_NAME }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
        run: |
          az functionapp deployment source config-zip \
            --resource-group "$RESOURCE_GROUP" \
            --name "$FUNCTION_APP_NAME" \
            --src function-package/function.zip
          
